// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMeN4bF2-f5eAnPKiXa_J4kjQJtY26Epc',
    appId: '1:58533336412:web:ea287aa1a24b281291dd99',
    messagingSenderId: '58533336412',
    projectId: 'playgo-fb8e8',
    authDomain: 'playgo-fb8e8.firebaseapp.com',
    storageBucket: 'playgo-fb8e8.firebasestorage.app',
    measurementId: 'G-GF1V8VYEPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6I12OxVYE0quSkQSGQzLJuRiU-T7ijv0',
    appId: '1:58533336412:android:b52ba10c545fabae91dd99',
    messagingSenderId: '58533336412',
    projectId: 'playgo-fb8e8',
    storageBucket: 'playgo-fb8e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGoyNeXuf0JDd9Iu92GeOP8RffT5P5_1A',
    appId: '1:58533336412:ios:5047969c82b00c2391dd99',
    messagingSenderId: '58533336412',
    projectId: 'playgo-fb8e8',
    storageBucket: 'playgo-fb8e8.firebasestorage.app',
    iosBundleId: 'com.example.playgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGoyNeXuf0JDd9Iu92GeOP8RffT5P5_1A',
    appId: '1:58533336412:ios:5047969c82b00c2391dd99',
    messagingSenderId: '58533336412',
    projectId: 'playgo-fb8e8',
    storageBucket: 'playgo-fb8e8.firebasestorage.app',
    iosBundleId: 'com.example.playgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMeN4bF2-f5eAnPKiXa_J4kjQJtY26Epc',
    appId: '1:58533336412:web:d1b67be6ab04503c91dd99',
    messagingSenderId: '58533336412',
    projectId: 'playgo-fb8e8',
    authDomain: 'playgo-fb8e8.firebaseapp.com',
    storageBucket: 'playgo-fb8e8.firebasestorage.app',
    measurementId: 'G-JVHRTN2ZQK',
  );
}
